- name: Docker Setup
  hosts: all
  become: yes

  tasks:

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
